<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).artifacts/dotnet/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory).artifacts/dotnet/bin/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>
</Project>
